version: "3.8"

services:
  payment-service:
    build:
      context: ./services/payment-service
      dockerfile: Dockerfile
    container_name: payment-service
    ports:
      - "5004:84"
    networks:
      - backend-network
    depends_on:
      - sqlserver
    environment:
      - DefaultConnection=Server=sqlserver;Database=db_mt_soa_payment_service;User Id=sa;Password=Strong!Pass123;Encrypt=False

networks:
  backend-network:
    driver: bridge
