version: "3.8"

services:
  auth-service:
    build:
      context: ./services/auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "5000:80"
    networks:
      - backend-network
    depends_on:
      - sqlserver
      - rabbitmq
    environment:
      - DefaultConnection=Server=sqlserver;Database=db_mt_soa_authentication_service;User Id=sa;Password=Strong!Pass123;Encrypt=False
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
networks:
  backend-network:
    driver: bridge
