services:
  authentication-service:
    build:
      context: ./services/auth-service
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    networks:
      - backend-network

  welcome-service:
    build:
      context: ./services/welcome-service
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    networks:
      - backend-network

  ordering-service:
    build:
      context: ./services/ordering-service
      dockerfile: Dockerfile
    ports:
      - "5002:80"
    networks:
      - backend-network

  payment-service:
    build:
      context: ./services/payment-service
      dockerfile: Dockerfile
    ports:
      - "5003:80"
    networks:
      - backend-network

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - backend-network

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend-network

  
networks:
  backend-network:
    driver: bridge
